Address feedback

diff --git a/rpm/stackdriver-agent b/rpm/stackdriver-agent
--- a/rpm/stackdriver-agent
+++ b/rpm/stackdriver-agent
@@ -84,8 +84,8 @@ check_config() {
         # See if the instance has the correct monitoring scopes.
         INSTANCE_SCOPES=$(curl --silent --connect-timeout 1 -f -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes 2>/dev/null || /bin/true)
         if [ `echo "$INSTANCE_SCOPES" | grep -cE '(monitoring.write|monitoring|cloud-platform)$'` -lt 1 ]; then
-            echo "The instance has neither the application default" \
-              "credentials file nor the correct monitoring scopes; Exiting." >&2
+            echo >&2 "The instance has neither the application default" \
+              "credentials file nor the correct monitoring scopes; Exiting."
             return 3
         fi
     else
@@ -110,7 +110,7 @@ start () {
     fi
 
     if ! check_config; then
-        echo "Not starting, configuration/credentials error." >&2
+        echo >&2 "Not starting, configuration/credentials error."
         return 1
     fi
 
